import type { ServiceCategorySlug } from '@/shared/constants/categories';
import type { CaseStudy } from '@/shared/types';

export const ALL_CASES: CaseStudy[] = [
  {
    slug: 'ai-lead-intake-crm-automation',
    category: 'ai-automation',
    shot: 'Lead management workflow screenshot',
    thumbnail: '/assets/lead-management.png',
    tag: 'AI Automation · CRM',
    title: 'AI-Powered Lead Intake & CRM Automation',
    desc: 'Automated the entire lead qualification workflow, JWT-secured ingestion, email verification, AI priority scoring, Google Sheets audit logging, and HubSpot CRM sync.',
    m1v: '100%',
    m1l: 'manual lead entry eliminated',
    m2v: '6×',
    m2l: 'faster lead response time',
    challenge:
      'The client was receiving inbound leads from multiple channels with no standardised validation or qualification process. Sales teams spent hours reviewing submissions, verifying emails, updating spreadsheets, and manually creating CRM contacts.',
    solution:
      'We designed an automated pipeline in n8n that validates, enriches, prioritises, logs, and routes every lead automatically, from a JWT-secured webhook to a clean HubSpot contact, without a human touching the data.',
    outcome:
      'Manual lead qualification was eliminated entirely. Sales teams now receive clean, prioritised contacts in HubSpot in seconds, with a full audit trail in Google Sheets and zero duplicate records.',
    tldr: [
      'Captures leads via secure JWT-authenticated webhooks',
      'Verifies email deliverability in real time with Hunter.io',
      'Uses OpenAI to classify and prioritise each inquiry',
      'Logs all activity and metadata to Google Sheets',
      'Syncs qualified leads into HubSpot, creates or updates contacts',
      'Eliminates all manual lead qualification and data entry',
    ],
    problemPoints: [
      'Leads arrived from web forms, email, and third-party sources with no unified intake process',
      'Sales teams spent hours daily reviewing, verifying, and manually entering leads into the CRM',
      'No email validation meant bad data and bounced outreach',
      'Delayed response times, leads would sit unactioned overnight and over weekends',
      'Duplicate CRM records from inconsistent manual entry',
      'No audit trail or visibility into lead quality over time',
    ],
    solutionPoints: [
      'JWT-authenticated webhook secures lead ingestion from any external source',
      'Hunter.io verifies email deliverability and domain reputation in real time',
      'OpenAI analyses the inquiry message and assigns a priority level (High / Medium / Low)',
      'All lead data, verification results, and AI insights are logged to Google Sheets',
      'Qualified leads are automatically created or updated in HubSpot CRM',
      'Conditional routing handles edge cases, unverified emails are flagged, not silently dropped',
    ],
    outcomePoints: [
      'Manual CRM data entry completely eliminated',
      'Lead response time reduced from hours to under 60 seconds',
      'Duplicate records dropped to zero with upsert logic in HubSpot',
      'Full audit trail in Google Sheets for every lead processed',
      'AI-driven prioritisation ensures the highest-value leads are visible first',
      'Workflow architecture scales to multiple lead sources without additional engineering',
    ],
    deliverySteps: [
      'Architected the end-to-end workflow in n8n and mapped all integration touchpoints',
      'Secured ingestion using JWT-authenticated webhooks with signature verification',
      'Integrated Hunter.io for real-time email verification on every submission',
      'Implemented OpenAI classification logic with structured output parsing',
      'Built conditional routing to separate qualified leads from unverified or low-quality ones',
      'Configured Google Sheets as the operational log store with timestamped rows',
      'Integrated HubSpot contact creation and update with duplicate detection',
      'Ran end-to-end testing across good data, bad emails, malformed payloads, and edge cases',
    ],
    testimonial: {
      quote: 'Before this, our sales team was spending hours every day just cleaning up lead data and manually pushing contacts into HubSpot. Silver Axis built us something that just runs. Leads come in, get verified, get scored, and land in the CRM ready to action. It has genuinely changed how our team operates.',
    },
    tools: ['n8n', 'OpenAI API', 'Hunter.io', 'HubSpot CRM', 'Google Sheets', 'Webhooks', 'JWT Authentication'],
    screenshots: [
      { src: '/assets/full workflow.png',   caption: 'Full n8n workflow, end-to-end pipeline' },
      { src: '/assets/webhook.png',         caption: 'JWT-secured webhook, lead ingestion' },
      { src: '/assets/hunter.png',          caption: 'Hunter.io, real-time email verification' },
      { src: '/assets/openAI.png',          caption: 'OpenAI, inquiry classification & prioritisation' },
      { src: '/assets/google sheets.png',   caption: 'Google Sheets, full audit log' },
      { src: '/assets/hubspot.png',         caption: 'HubSpot CRM, contact creation & sync' },
    ],
  },
  {
    slug: 'meemint-crm',
    category: 'custom-systems',
    shot: 'MeemInt CRM dashboard screenshot',
    thumbnail: '/assets/meemInt-thumbnail.png',
    tag: 'Custom CRM',
    title: 'MeemInt, Transport & Hotel CRM',
    desc: 'A custom CRM portal built on the MERN stack centralising booking management, customer records, invoicing, route planning, and fleet operations for transport and hotel businesses in one unified platform.',
    m1v: 'MERN',
    m1l: 'full-stack',
    m2v: '100%',
    m2l: 'custom-built',
    challenge:
      'Transport and hotel operations were managed across disconnected tools, bookings in spreadsheets, customer records in separate files, invoices generated manually, and fleet data tracked informally. There was no single source of truth, no real-time visibility, and no way to enforce access controls across teams.',
    solution:
      'We designed and built a custom MERN stack CRM portal that centralises every operational function, bookings, customer records, invoicing, route planning, and fleet management, into a single responsive platform with role-based access and real-time dashboards.',
    outcome:
      'A modern, unified operations platform that replaced fragmented tools with a single source of truth, improving booking accuracy, reducing manual effort, and giving management real-time visibility across both transport and hotel operations.',
    tldr: [
      'Custom CRM built on the MERN stack (MongoDB, Express.js, React, Node.js)',
      'Centralised booking management, customer records, invoicing, and fleet operations',
      'Route planning module integrated directly into the operational workflow',
      'Responsive dashboards with real-time data visualisation and reporting',
      'Role-based access control, staff see only what they need',
      'Scalable architecture designed to grow with the business',
    ],
    problemPoints: [
      'Bookings managed across spreadsheets and informal tools, no unified system',
      'Customer records stored in separate files with no searchable history or audit trail',
      'Invoices generated manually, time-consuming, error-prone, and inconsistent',
      'Fleet and route planning handled informally with no visibility into availability or scheduling',
      'No role-based access, all staff had access to all data regardless of their function',
      'No real-time reporting, management had no live view of operational performance',
      'Disconnected hotel and transport operations with no shared data layer',
    ],
    solutionPoints: [
      'MERN stack CRM built from scratch, MongoDB, Express.js, React, Node.js',
      'Centralised booking module covering creation, modification, confirmation, and history',
      'Customer record management with searchable profiles, booking history, and notes',
      'Invoicing system with automated generation, PDF export, and payment status tracking',
      'Route planning module with fleet assignment and scheduling built in',
      'Role-based access control, granular permissions per user role across all modules',
      'Real-time dashboards with live data visualisation and exportable reports',
      'Responsive UI designed for both desktop operations and mobile management access',
    ],
    outcomePoints: [
      'All transport and hotel operations unified in a single platform',
      'Booking accuracy improved with a structured, validated intake workflow',
      'Manual invoicing eliminated, automated generation with payment tracking',
      'Fleet and route visibility available in real time to operations staff',
      'Role-based access enforced across every module, right data, right people',
      'Management dashboards provide live operational reporting without manual aggregation',
      'Scalable architecture ready for additional business units or locations',
    ],
    deliverySteps: [
      'Discovery sessions to map all operational workflows across transport and hotel functions',
      'Designed system architecture: MERN stack with role-based auth and modular service layer',
      'UI/UX design, responsive layouts, dashboard wireframes, and user workflow prototyping',
      'Built the React frontend with real-time data visualisation components',
      'Developed the Node.js/Express.js backend with RESTful API layer',
      'Configured MongoDB schema for bookings, customers, invoices, routes, and fleet records',
      'Implemented role-based access control with JWT authentication',
      'Built invoicing module with automated PDF generation and payment status tracking',
      'Integrated route planning and fleet management modules',
      'End-to-end QA, performance testing, and responsive design validation',
      'Deployment and handover with documentation for ongoing management',
    ],
    testimonial: {
      quote: 'I kept saying we would sort out the spreadsheet situation eventually. Silver Axis actually sorted it. The system is clean, the team picked it up fast, and I genuinely cannot imagine going back.',
    },
    tools: ['React', 'Node.js', 'MongoDB', 'Express', 'TypeScript', 'Docker'],
    screenshots: [
      { src: '/assets/mi (1).png', caption: 'MeemInt CRM, main dashboard overview' },
      { src: '/assets/mi (2).png', caption: 'Booking management and customer records' },
      { src: '/assets/mi (3).png', caption: 'Reporting and data visualisation' },
    ],
  },
  {
    slug: 'trade-with-allah',
    category: 'web-mobile',
    shot: 'Trade with ALLAH app screenshot',
    thumbnail: '/assets/Trade with ALLAH.png',
    tag: 'Web + Mobile',
    title: 'Trade with ALLAH',
    desc: 'Trade With Allah is a faith-driven platform that connects those seeking assistance with trusted volunteers in their local community. Using smart location matching and real-time notifications, the platform enables faster support, transparent coordination, and meaningful acts of kindness that create lasting impact.',
    m1v: 'Live',
    m1l: 'on App Store & Play Store',
    m2v: '24/7',
    m2l: 'community support',
    liveUrl: 'https://apps.apple.com/pk/app/trade-with-allah/id6757193179',
    challenge:
      'Many individuals and families face urgent needs but struggle to find timely help. At the same time, people willing to volunteer often do not know who needs assistance nearby. This disconnect leads to delayed support, fragmented efforts, and missed opportunities to make a meaningful difference.',
    solution:
      'We built Trade With Allah, a faith-driven mobile platform where beneficiaries create assistance requests with photos, voice notes, or videos, and verified volunteers receive real-time notifications for nearby requests matching their categories and availability.',
    outcome:
      'A trusted, location-aware volunteer network that connects people in need with community helpers faster than any informal channel, with full accountability, category-based filtering, and real-time request tracking from submission to completion.',
    tldr: [
      'Faith-driven platform connecting people in need with trusted local volunteers',
      'Smart location-based matching surfaces the right volunteers for each request',
      'Assistance requests support photos, voice notes, and videos for full context',
      'Category-based requests, Food, Medicine, Education, Financial Aid, Transportation, and more',
      'Verified volunteer approval system ensures trust and accountability',
      'Real-time notifications, in-app communication, and request tracking to completion',
      'Secure login with biometric authentication and OTP verification',
      'Full development lifecycle: requirements, design, development, QA, App Store submission',
    ],
    problemPoints: [
      'People in urgent need had no reliable way to quickly find help in their local community',
      'Willing volunteers had no visibility into who needed assistance nearby',
      'Assistance efforts were fragmented across WhatsApp groups, word of mouth, and informal channels',
      'No verification system, beneficiaries had no way to trust who was responding to their request',
      'Requests lacked structure, no categories, no media support, no way to communicate context clearly',
      'No tracking, once a request was made, there was no visibility into status or progress',
      'Community engagement was inconsistent and geographically uncoordinated',
    ],
    solutionPoints: [
      'Beneficiaries create structured assistance requests with photos, voice notes, and video for full context',
      'Category-based system (Food, Medicine, Education, Financial Aid, Transportation, and more) for precise matching',
      'Smart location-based matching notifies verified volunteers about nearby relevant requests in real time',
      'Verified volunteer approval system, every volunteer is reviewed before accessing the platform',
      'In-app communication unlocked after a volunteer accepts a request, keeping coordination on-platform',
      'Real-time request tracking from pending through to completed, visible to both parties',
      'Instant push notifications for new opportunities matching a volunteer\'s selected categories and availability',
      'Biometric authentication (Face ID / fingerprint) and OTP verification for fast, secure sign-in',
    ],
    outcomePoints: [
      'Launched live on iOS App Store and Google Play Store',
      'Faster response times for people in need through location-aware volunteer matching',
      'Verified and accountable volunteer network, trust built into the platform by design',
      'Structured request format ensures volunteers arrive with full context and the right resources',
      'Community engagement increased through category filtering and relevant notifications',
      'Full request lifecycle tracked in-app, no lost requests, no ambiguity on status',
      'Faith-driven mission embedded in the product design and user experience',
    ],
    deliverySteps: [
      'Stakeholder workshops to map beneficiary and volunteer journeys end-to-end',
      'Defined system architecture: location-based matching engine, real-time notifications, media uploads',
      'UI/UX design, wireframes, interactive prototypes, and usability testing',
      'Built the cross-platform mobile app (iOS + Android)',
      'Implemented smart location-based matching between beneficiaries and volunteers',
      'Built category-based request and filtering system with media attachment support',
      'Integrated verified volunteer approval workflow for trust and accountability',
      'Developed real-time notification system and in-app communication after acceptance',
      'Implemented biometric authentication (Face ID / fingerprint) and OTP verification',
      'Brute-force testing, route testing, and performance optimisation',
      '14-day closed beta on Play Store, privacy policy and T&C documentation',
      'Submitted and released on App Store and Google Play Store',
      'Post-launch maintenance and issue resolution',
    ],
    testimonial: {
      quote: 'The app does exactly what we needed it to do, it connects people who need help with people who want to help, and it does it quickly. The location matching works well, the notification system is reliable, and the overall experience is clean. Silver Axis delivered everything we asked for and were great to work with throughout.',
    },
    tools: ['React Native', 'Node.js', 'PostgreSQL', 'Firebase', 'TypeScript', 'Google Maps API'],
    screenshots: [
      { src: '/assets/twa (1).png', caption: 'Home, request feed and navigation' },
      { src: '/assets/twa (5).png', caption: 'Request detail, location, media, and volunteer info' },
      { src: '/assets/twa (6).png', caption: 'Sign in, biometric and OTP authentication' },
      { src: '/assets/twa (7).png', caption: 'Accept & help, volunteer request flow' },
      { src: '/assets/twa (8).png', caption: 'Ask for help, category and location selection' },
    ],
  },
  {
    slug: 'smart-backload',
    category: 'web-mobile',
    shot: 'SmartBackload app screenshot',
    thumbnail: '/assets/screens-SB.png',
    tag: 'Web + Mobile',
    title: 'Smart Backload',
    desc: 'Smart Backload connects available trucks with freight in real time to eliminate empty return trips. Transporters share capacity, brokers post bids, and intelligent matching ensures fast, efficient deals, boosting utilization, reducing costs, and improving delivery speed.',
    m1v: 'Live',
    m1l: 'on App Store & Play Store',
    m2v: '60s',
    m2l: 'to post a load',
    liveUrl: 'https://smartbackload.com',
    challenge:
      'A large portion of trucks return empty after completing deliveries, costing transporters earnings and leaving brokers scrambling to find reliable capacity at short notice. There was no structured marketplace to connect the two sides in real time.',
    solution:
      'We designed and built Smart Backload, a cross-platform mobile app and web platform where transporters publish available capacity through Auction or RFQ modes, and brokers bid or submit quotes in a live, competitive environment with intelligent matching.',
    outcome:
      'Smart Backload launched on both the App Store and Google Play Store. Transporters fill empty return trips with paying loads, brokers get faster and more reliable access to capacity, and the platform handles the entire deal lifecycle from posting to finalisation.',
    tldr: [
      'Real-time freight marketplace connecting transporters and freight brokers',
      'Auction and RFQ (Request for Quotation) modes for structured, competitive pricing',
      'Cross-platform mobile app (iOS + Android) and responsive web platform',
      'Secure login with Face ID / fingerprint + WhatsApp OTP authentication',
      'Load posted in under 60 seconds with templates and one-click reposting',
      'Smart auction engine: prevents last-minute bids, handles drop-offs, next-bidder consent flow',
      'Dual-role system, users switch between broker and transporter seamlessly',
      'Real-time notifications for all key events across the deal lifecycle',
    ],
    problemPoints: [
      'Trucks completing deliveries return empty, wasted capacity and lost earnings for transporters',
      'Brokers and shippers had no structured channel to quickly find reliable available trucks',
      'No transparent pricing mechanism, deals were informal, inconsistent, and slow to close',
      'Logistics coordination happened across scattered phone calls, WhatsApp groups, and spreadsheets',
      'No audit trail or record of bids, quotes, or deal history for either party',
      'Repeat shipments on frequent routes required starting the whole process from scratch each time',
    ],
    solutionPoints: [
      'Transporters publish available capacity with route, timing, and capacity details in under 60 seconds',
      'Auction mode lets brokers compete in a live bidding environment with anti-snipe rules and drop-off handling',
      'RFQ mode lets brokers submit private quotes for structured, negotiated deals',
      'Dual-role account system, a single user can act as both broker and transporter with a one-tap role switch',
      'Load templates and one-click reposting eliminate repetitive data entry for frequent routes',
      'Contact details hidden until a deal is finalised, protecting both parties throughout the bidding process',
      'WhatsApp OTP + biometric login (Face ID / fingerprint) for fast, secure authentication',
      'Real-time push notifications keep both parties updated at every stage of the deal',
    ],
    outcomePoints: [
      'Live on iOS App Store and Google Play Store',
      'Empty return trips turned into revenue-generating loads for transporters',
      'Brokers access a competitive, transparent marketplace instead of scattered phone calls',
      'Load posting takes under 60 seconds, templates and reposting eliminate repetitive work',
      'Smart auction engine ensures fair, tamper-resistant deal closure',
      'Dual-role system removes friction for logistics professionals who operate on both sides',
      'Full deal history and audit trail available in-app for both parties',
    ],
    deliverySteps: [
      'Stakeholder workshops to map the full broker and transporter journey end-to-end',
      'Defined high-level architecture: mobile-first, cross-platform, real-time event-driven core',
      'UI/UX design, wireframes, interactive prototypes, and usability iterations',
      'Built the cross-platform mobile app (iOS + Android) and responsive web platform',
      'Implemented auction engine with anti-snipe rules, drop-off handling, and next-bidder consent flow',
      'Integrated WhatsApp OTP and biometric authentication (Face ID / fingerprint)',
      'Built real-time notification system for all deal lifecycle events',
      'Implemented load templates, one-click reposting, and dual-role account switching',
      'Brute-force and route testing, performance optimisation, and QA sign-off',
      '14-day closed beta on Play Store, privacy policy and T&C documentation',
      'Submitted and released on App Store and Google Play Store',
      'Post-launch maintenance and prompt issue resolution',
    ],
    testimonial: {
      quote: 'The auction logic is genuinely impressive. Anti-snipe rules, drop-off handling, next-bidder flow, it all just works. We had drivers posting loads on day one without any hand-holding.',
    },
    tools: ['React Native', 'Node.js', 'PostgreSQL', 'WebSockets', 'Firebase', 'TypeScript'],
    screenshots: [
      { src: '/assets/screens-SB.png',        caption: 'Smart Backload, app screens overview' },
      { src: '/assets/Website -SB.jpeg',      caption: 'Smart Backload, web platform' },
      { src: '/assets/Play Store -SB.jpeg',   caption: 'Smart Backload, Google Play Store listing' },
      { src: '/assets/App store -SB.PNG',     caption: 'Smart Backload, Apple App Store listing' },
    ],
  },
  {
    slug: 'whatsapp-automation-platform',
    category: 'ai-automation',
    shot: 'WhatsApp automation workflow screenshot',
    thumbnail: '/assets/thumbail_wa.png',
    tag: 'AI Automation · Messaging',
    title: 'WhatsApp-Based Workflow Automation Platform',
    desc: 'Converted unstructured WhatsApp messaging into a fully structured workflow system, state-based routing, AI-powered localization, geolocation processing, and Airtable as the central data layer.',
    m1v: '100%',
    m1l: 'WhatsApp-native UX',
    m2v: '24/7',
    m2l: 'automated handling',
    challenge:
      'The client needed a way for users to interact with a structured workflow system without leaving WhatsApp. Incoming messages were unstructured, multi-step conversations needed to maintain state, and the platform had to support multiple languages and location-based inputs, all without a traditional app or web interface.',
    solution:
      'We built a modular automation platform on a self-hosted n8n server, integrated with the WhatsApp Business API and Airtable as the central database. Incoming messages are routed through state-based logic, AI handles translation for multilingual users, and geolocation inputs are parsed into structured data, all transparently within WhatsApp.',
    outcome:
      'Users interact with the entire platform through WhatsApp with no app download required. The modular n8n architecture handles message routing, state management, notifications, and automated responses reliably at scale, and new workflow sequences can be added without touching the core system.',
    tldr: [
      'Replaced manual WhatsApp group coordination with a fully automated chatbot',
      'State-based routing handles every inbound message, no human assignment needed',
      'Dynamic volunteer matching queries Airtable in real time to find the right person',
      'Edge cases, timeouts, and unrecognised inputs handled gracefully in every flow',
      'AI translation delivers messages in the user\'s language automatically',
      'Full audit trail logged to Airtable, every request, assignment, and outcome recorded',
    ],
    problemPoints: [
      'All coordination happened in WhatsApp group chats, requests, assignments, and follow-ups were buried in conversation threads',
      'Staff manually read every incoming message and assigned it to the right person or team by hand',
      'No conversation state, users had to repeat context every time they sent a new message',
      'Volunteer matching was done manually by scrolling through availability lists and guessing availability',
      'Multi-language users were either ignored or required a bilingual staff member to relay messages',
      'Location data was shared as raw pins with no way to process or act on it programmatically',
      'Missed messages, duplicate assignments, and dropped requests were a regular occurrence',
      'Zero audit trail, no record of who was assigned what, when, or what the outcome was',
    ],
    solutionPoints: [
      'Replaced group chat chaos with a WhatsApp chatbot that handles every inbound message automatically, no human needed for routing',
      'State-based conversation engine remembers where each user is in a workflow, so context is never lost between messages',
      'Automated routing directs each request to the correct workflow path based on message content and user state',
      'Dynamic volunteer matching engine queries Airtable in real time to find and assign the best-fit volunteer based on availability and criteria',
      'Edge case handling built into every workflow, unrecognised inputs, incomplete responses, and timeouts are caught and resolved gracefully',
      'AI translation layer detects language and localises all outbound messages, no bilingual staff required',
      'Geolocation processing converts raw location pins into structured geographic data used directly in matching and routing logic',
      'Full audit trail in Airtable, every interaction, assignment, and outcome logged with timestamps for reporting and accountability',
    ],
    outcomePoints: [
      'Manual group chat coordination fully replaced, staff no longer read and route messages by hand',
      'Volunteer matching automated end-to-end, right person assigned in seconds, not minutes',
      'Zero missed or dropped requests, every message enters the workflow and is tracked to resolution',
      'Multilingual users served automatically with no bilingual staff dependency',
      'Full operational visibility, every interaction, assignment, and outcome logged in Airtable',
      'Modular architecture means new workflow sequences ship independently without touching core logic',
    ],
    deliverySteps: [
      'Mapped all user interaction flows and designed the state machine architecture',
      'Set up self-hosted n8n server and configured WhatsApp Business API webhook integration',
      'Built the state-based message routing engine to evaluate and direct incoming messages',
      'Designed Airtable schema for user data, workflow state, and request tracking',
      'Integrated AI translation service for real-time multilingual message localisation',
      'Implemented geolocation processing module to parse and structure location inputs',
      'Built modular workflow blocks for each interaction sequence (registration, routing, notifications)',
      'Tested end-to-end flows across multiple languages, location inputs, and conversation states',
    ],
    testimonial: {
      quote: 'I had a very positive experience working with Silver Axis. They successfully completed the assigned project with great professionalism and patience. Throughout the process, they were responsive, attentive, and easy to communicate with. Their dedication and professional attitude made the collaboration smooth and enjoyable. I will definitely work with them again in the future.',
    },
    tools: ['n8n', 'WhatsApp Business API', 'Airtable', 'OpenAI API'],
    screenshots: [
      { src: '/assets/whatsapp_n8n_workflow.png',           caption: 'Main n8n workflow, WhatsApp message orchestration' },
      { src: '/assets/whatsapp_chat_registration_flow.png', caption: 'Chat registration flow, state-based onboarding' },
      { src: '/assets/whatsapp_volunteer_approval_flow.png', caption: 'Volunteer approval flow, multi-step routing' },
      { src: '/assets/airtable_requests_table.png',         caption: 'Airtable, requests table & audit log' },
      { src: '/assets/airtable_automation_agent.png',       caption: 'Airtable, automation agent configuration' },
    ],
  },
  {
    slug: 'eod-report-automation',
    category: 'ai-automation',
    shot: 'EOD Report Generation workflow screenshot',
    thumbnail: '/assets/EOD thumbnail.png',
    tag: 'AI Automation · Reporting',
    title: 'Automated EOD Report Generation',
    desc: 'Daily End-of-Day reports generated automatically, ClickUp tasks and GoHighLevel sales data fetched, merged, and summarised by AI, then pushed to Slack, Email, and Google Drive every weekday at 6 PM.',
    m1v: '100%',
    m1l: 'manual reporting eliminated',
    m2v: 'Daily',
    m2l: 'automated at 6 PM',
    challenge:
      'The team was manually compiling EOD reports each evening, pulling task data from ClickUp, sales figures from GoHighLevel, writing summaries, and distributing them across Slack, email, and shared drives. It was repetitive, error-prone, and took 30–60 minutes every day.',
    solution:
      'We built an n8n workflow triggered on a schedule every weekday at 6 PM. It fetches live data from ClickUp and GoHighLevel, merges and formats the records, passes them to Google Gemini for an AI-generated narrative summary, then distributes the final report to Slack, Email, and Google Drive automatically.',
    outcome:
      'EOD reporting is now fully hands-off. The team receives a consistent, AI-written summary every evening with zero manual effort, covering task completions, sales progress, and actionable next steps.',
    tldr: [
      'Scheduled trigger fires every weekday at 6 PM',
      'Fetches task data from ClickUp and sales data from GoHighLevel',
      'Merges and formats raw data for analysis',
      'Google Gemini generates a structured AI narrative summary',
      'Report distributed automatically via Slack, Email, and Google Drive',
      'Eliminates 30–60 minutes of manual reporting per day',
    ],
    problemPoints: [
      'EOD reports compiled manually every evening, taking 30–60 minutes of team time',
      'Data pulled from two separate platforms (ClickUp + GoHighLevel) with no unified view',
      'Summaries were inconsistent in quality and format depending on who wrote them',
      'Reports were sometimes delayed or missed when team was busy',
      'No automated distribution, manually sent to Slack and email each time',
      'No structured archive of historical EOD reports for trend analysis',
    ],
    solutionPoints: [
      'Scheduled n8n workflow runs automatically at 6 PM every weekday, no manual trigger needed',
      'ClickUp API fetches all task completions and updates for the day',
      'GoHighLevel API retrieves current sales pipeline and deal activity',
      'Data is merged, cleaned, and structured into a consistent format',
      'Google Gemini generates a narrative summary covering tasks, sales, and action items',
      'Report is pushed simultaneously to Slack channel, email recipients, and a Google Drive folder',
    ],
    outcomePoints: [
      'Manual EOD report compilation fully eliminated',
      'Consistent, professional report format delivered every evening without fail',
      'AI-generated summaries highlight key wins, blockers, and next-day priorities',
      'Historical reports automatically archived in Google Drive for trend review',
      'Team receives Slack notification the moment the report is ready',
      'Workflow architecture is reusable, easily adapted for weekly or monthly reporting',
    ],
    deliverySteps: [
      'Mapped all data sources and designed the unified report schema',
      'Built ClickUp API integration to pull daily task activity',
      'Built GoHighLevel API integration for sales pipeline data',
      'Implemented data merging and formatting layer in n8n',
      'Integrated Google Gemini for AI-driven narrative report generation',
      'Configured Slack bot to post formatted report to the team channel',
      'Set up email distribution with HTML-formatted report body',
      'Configured Google Drive upload for automated archiving',
      'Scheduled the full workflow at 6 PM weekdays with error alerting',
    ],
    testimonial: {
      quote: '6 PM. Every day. Report in Slack. It has not missed once.',
    },
    tools: ['n8n', 'Google Gemini', 'ClickUp', 'GoHighLevel', 'Slack', 'Google Drive'],
    screenshots: [
      { src: '/assets/Full workflow - EOD.PNG', caption: 'Full n8n EOD report workflow, end-to-end pipeline' },
      { src: '/assets/Clickup.PNG',             caption: 'ClickUp, daily task completion data fetch' },
      { src: '/assets/GHL.PNG',                 caption: 'GoHighLevel, sales pipeline data retrieval' },
      { src: '/assets/Slack.PNG',               caption: 'Slack, automated report distribution' },
      { src: '/assets/Email.PNG',               caption: 'Email, formatted EOD report delivery' },
    ],
  },
  {
    slug: 'blackcat-marketing-website',
    category: 'web-mobile',
    shot: 'BlackCat Marketing website screenshot',
    thumbnail: '/assets/Black_cat_website (3).png',
    tag: 'Web Design · Marketing',
    title: 'Marketing Agency Website Design',
    desc: 'A modern marketing agency website built for lead generation, with conversion-focused service pages, clear CTAs, and a fully responsive experience across desktop, tablet, and mobile.',
    m1v: 'Live',
    m1l: 'production site',
    m2v: '4',
    m2l: 'conversion pillars',
    liveUrl: 'https://blackcat.marketing/',
    challenge:
      'BlackCat Marketing needed a website that matched the quality of their paid media and analytics work, but their previous presence did not reflect their positioning or convert visitors into audit requests. Service offerings were hard to scan, CTAs were buried, and the experience was not consistent across devices.',
    solution:
      'We designed and developed a custom marketing agency website focused on lead generation and clarity. The site introduces the brand with a strong hero message, breaks services into four conversion pillars, and guides visitors through a structured journey from problem awareness to booking a forensic review.',
    outcome:
      'A polished, responsive marketing site that presents BlackCat\'s expertise with confidence, makes services easy to understand, and supports lead capture with clear calls-to-action throughout the user journey.',
    tldr: [
      'Designed and developed a modern marketing agency website',
      'Custom UI/UX focused on lead generation and conversions',
      'Fully responsive experience for desktop, tablet, and mobile',
      'Strategic service pages and conversion-focused layouts',
      'Clear calls-to-action and optimized user journeys',
      'Consistent branding, typography, and visual identity',
    ],
    problemPoints: [
      'The existing site did not reflect the agency\'s premium positioning or operator-led expertise',
      'Service offerings were difficult to scan, visitors could not quickly understand what BlackCat does',
      'Lead generation paths were unclear, with weak or inconsistent calls-to-action',
      'Mobile and tablet layouts needed improvement for prospects browsing on the go',
      'Brand identity, typography, and visual hierarchy were not cohesive across pages',
      'No structured way to guide visitors from awareness to booking a forensic review',
    ],
    solutionPoints: [
      'Designed and developed a modern marketing agency website with a conversion-first layout',
      'Created custom UI/UX focused on lead generation, clarity, and trust-building',
      'Built a fully responsive experience for desktop, tablet, and mobile breakpoints',
      'Developed strategic service pages organized around four core pillars of profit',
      'Implemented clear calls-to-action and optimized user journeys from hero to contact',
      'Maintained consistent branding, typography, and visual identity across the site',
      'Enhanced performance, usability, and overall user experience for faster page engagement',
    ],
    outcomePoints: [
      'Live production website at blackcat.marketing',
      'Services are presented in a scannable, conversion-focused structure',
      'Visitors can move from problem awareness to audit request in fewer steps',
      'Responsive layouts deliver a consistent experience on every device',
      'Brand presentation now matches the quality of the agency\'s client work',
      'Improved usability and page flow support longer engagement and stronger lead intent',
    ],
    deliverySteps: [
      'Discovery sessions to define positioning, audience, and conversion goals',
      'Mapped user journeys from homepage hero to service pages and contact actions',
      'UI/UX design for homepage, service pillars, about story, and contact flows',
      'Built responsive layouts for desktop, tablet, and mobile',
      'Developed conversion-focused service pages with clear CTAs and structured content',
      'Applied consistent branding, typography, and visual identity across all sections',
      'Performance and usability pass before launch',
      'Deployed live site and validated key user flows end to end',
    ],
    testimonial: {
      quote: 'The new site finally looks like the level of work we deliver for clients. Clean, direct, and built to convert. Prospects understand what we do within seconds.',
    },
    tools: ['Figma', 'React', 'Tailwind CSS', 'Vercel'],
    screenshots: [
      { src: '/assets/Black_cat_website (1).png', caption: 'Homepage, hero and conversion messaging' },
      { src: '/assets/Black_cat_website (2).png', caption: 'Service pillars and lead generation layout' },
    ],
  },
  {
    slug: 'ue-motors-dealership',
    category: 'web-mobile',
    shot: 'UE Motors dealership website screenshot',
    thumbnail: '/assets/EUMtoros_Thumbnail.png',
    tag: 'Web + Backend',
    title: 'UE Motors, Car Dealership Website',
    desc: 'A modern car dealership website for UE Motors, a UK-based used vehicle dealer, with intuitive inventory search, finance and part-exchange flows, and a backend built on PostgreSQL and deployed on AWS.',
    m1v: 'UK',
    m1l: 'used vehicle dealer',
    m2v: 'AWS',
    m2l: 'production deployment',
    liveUrl: 'https://www.uemotors.co.uk/',
    challenge:
      'UE Motors needed a professional online presence to showcase used vehicle stock, but their previous setup made it hard for buyers to browse inventory, enquire about vehicles, or explore finance and part-exchange options. Listings were difficult to manage, and the experience did not work well across mobile devices.',
    solution:
      'We designed and developed a modern dealership website with an intuitive vehicle inventory and search experience, integrated stock listings, finance, part-exchange, and inquiry sections, backed by a PostgreSQL database and deployed on AWS for reliable performance.',
    outcome:
      'A responsive, conversion-focused dealership platform that helps UE Motors showcase inventory professionally, capture vehicle enquiries, and give buyers a smooth path from browsing to contact across desktop, tablet, and mobile.',
    tldr: [
      'Designed and developed a modern car dealership website for UE Motors',
      'Built an intuitive vehicle inventory and search experience',
      'Responsive layouts optimized for desktop, tablet, and mobile',
      'Integrated stock listings, finance, part-exchange, and vehicle inquiry sections',
      'PostgreSQL backend for inventory and enquiry management',
      'Deployed on AWS for reliable production hosting',
    ],
    problemPoints: [
      'Used vehicle stock was hard to browse and search online, limiting buyer engagement',
      'No structured way for customers to enquire about specific vehicles from listing pages',
      'Finance, part-exchange, and inquiry journeys were missing or disconnected',
      'Mobile browsing experience did not match how most car buyers research vehicles',
      'Inventory updates required manual effort with no reliable backend system',
      'The dealership lacked a professional online presence to support lead generation',
    ],
    solutionPoints: [
      'Designed and developed a modern car dealership website for UE Motors, a UK-based used vehicle dealer',
      'Built an intuitive vehicle inventory and search experience for fast stock discovery',
      'Created responsive layouts optimized for desktop, tablet, and mobile devices',
      'Integrated stock listings, finance, part-exchange, and vehicle inquiry sections',
      'Implemented a PostgreSQL backend to manage inventory, enquiries, and operational data',
      'Deployed the platform on AWS for scalable, reliable production hosting',
      'Focused on user experience, lead generation, and conversion optimization throughout',
    ],
    outcomePoints: [
      'Professional online presence that showcases inventory with clarity and trust',
      'Buyers can search stock and submit vehicle enquiries with fewer steps',
      'Finance and part-exchange sections support stronger conversion paths',
      'Responsive experience works consistently across desktop, tablet, and mobile',
      'Backend on PostgreSQL gives the dealership a reliable system for listings and leads',
      'AWS deployment supports stable performance for customer-facing traffic',
    ],
    deliverySteps: [
      'Discovery sessions to map inventory, enquiry, finance, and part-exchange workflows',
      'UI/UX design for homepage, stock listings, vehicle detail pages, and enquiry flows',
      'Built responsive frontend layouts for desktop, tablet, and mobile',
      'Developed vehicle inventory search, filtering, and listing detail experiences',
      'Integrated finance, part-exchange, and vehicle inquiry sections',
      'Built PostgreSQL backend for stock management and customer enquiry handling',
      'Configured AWS deployment for production hosting and reliability',
      'Tested key user journeys and launched the live dealership platform',
    ],
    testimonial: {
      quote: 'Our old site was basically a brochure nobody used. Now people actually browse stock on their phone and message us about specific cars. Still getting used to updating listings ourselves, but it beats chasing someone every time we sell a motor.',
    },
    tools: ['React', 'Node.js', 'PostgreSQL', 'AWS', 'TypeScript', 'Tailwind CSS'],
    screenshots: [
      { src: '/assets/EUMotors (1).png', caption: 'Homepage and dealership branding' },
      { src: '/assets/EUMotors (2).png', caption: 'Vehicle inventory and search experience' },
      { src: '/assets/EUMotors (3).png', caption: 'Vehicle detail, finance, and enquiry flow' },
    ],
  },
];

export const HOME_CASES = ALL_CASES.slice(0, 2);

export function getCaseStudyBySlug(slug: string): CaseStudy | undefined {
  return ALL_CASES.find((cs) => cs.slug === slug);
}

export function filterCaseStudiesByCategory(category: ServiceCategorySlug | null): CaseStudy[] {
  if (!category) return ALL_CASES;
  return ALL_CASES.filter((cs) => cs.category === category);
}

export function getRelatedCaseStudies(slug: string, limit = 3): CaseStudy[] {
  const current = getCaseStudyBySlug(slug);
  if (!current) return [];
  return ALL_CASES.filter((cs) => cs.slug !== slug && cs.category === current.category).slice(0, limit);
}
