import type { ServiceCategorySlug } from '@/shared/constants/categories';
import type { IndustrySlug } from '@/shared/constants/industries';
import type { CaseStudy } from '@/shared/types';

export const ALL_CASES: CaseStudy[] = [
  {
    slug: 'blackcat-marketing-agency',
    industry: 'marketing-agencies',
    services: ['web-mobile', 'ai-automation'],
    shot: 'BlackCat Marketing website and automation workflow screenshot',
    thumbnail: '/assets/Black_cat_website (3).png',
    tag: 'Web Design · AI Automation',
    title: 'BlackCat Marketing, Website Redesign & Back-Office Automation',
    desc: 'A conversion-focused website rebuild paired with two automations that run the agency\'s back office, an AI-scored lead intake pipeline into HubSpot, and a daily EOD report pulled from ClickUp and GoHighLevel and written up by AI every evening at 6 PM.',
    m1v: 'Live',
    m1l: 'production site + automations',
    m2v: '30–60 min',
    m2l: 'manual reporting eliminated per day',
    liveUrl: 'https://blackcat.marketing/',
    challenge:
      'BlackCat Marketing\'s public site did not reflect the quality of their paid media and analytics work, services were hard to scan and CTAs were buried, so visitors were not converting into audit requests. Behind the scenes, the team was losing 30–60 minutes every evening manually compiling End-of-Day reports from ClickUp and GoHighLevel, and inbound leads from the site had no structured qualification step before landing, or failing to land, in HubSpot.',
    solution:
      'We rebuilt the agency\'s website around a conversion-first structure organised into four service pillars, then layered two automations on top of it. A scheduled n8n workflow now fetches ClickUp task data and GoHighLevel sales data every weekday at 6 PM, merges it, and hands it to Google Gemini to write a narrative EOD summary that lands in Slack, email and Google Drive. Separately, a JWT-secured intake pipeline verifies every inbound lead\'s email with Hunter.io, scores the inquiry with OpenAI, logs the full trail to Google Sheets, and syncs qualified contacts straight into HubSpot.',
    outcome:
      'BlackCat now has a site that matches the calibre of the work they sell to clients, an EOD report that has "not missed once", and a lead pipeline where qualified contacts land in HubSpot in seconds instead of sitting in an inbox for manual review.',
    tldr: [
      'Rebuilt the agency website around four conversion-focused service pillars',
      'Fully responsive experience across desktop, tablet and mobile',
      'Scheduled n8n workflow compiles ClickUp + GoHighLevel data every weekday at 6 PM',
      'Google Gemini writes a narrative EOD summary distributed to Slack, email and Drive',
      'JWT-secured webhook verifies and scores every inbound lead before it touches the CRM',
      'Hunter.io verifies email deliverability, OpenAI scores inquiry priority',
      'Qualified leads sync automatically into HubSpot with zero duplicate records',
      'Eliminates 30–60 minutes of manual reporting and all manual lead entry',
    ],
    problemPoints: [
      'The existing site did not reflect the agency\'s premium positioning, services were hard to scan and CTAs were buried',
      'Mobile and tablet layouts needed work for prospects browsing on the go',
      'EOD reports were compiled manually every evening from two separate platforms, ClickUp and GoHighLevel, with no unified view',
      'Report quality and format varied depending on who wrote it, and reports were sometimes late or missed',
      'Inbound leads had no email verification, so bad data and bounced outreach were common',
      'Sales spent hours reviewing submissions and manually creating HubSpot contacts, with duplicate records a regular occurrence',
      'No audit trail for either the reporting process or the lead pipeline',
    ],
    solutionPoints: [
      'Designed and built a conversion-first website with four core service pillars and clear calls-to-action end to end',
      'Fully responsive layouts across desktop, tablet and mobile breakpoints',
      'Scheduled n8n workflow triggers every weekday at 6 PM with no manual step',
      'ClickUp and GoHighLevel APIs feed a merge-and-format layer that structures the day\'s activity',
      'Google Gemini generates a narrative summary covering tasks, sales movement and next-day priorities',
      'Report is pushed simultaneously to Slack, email and a Google Drive archive',
      'JWT-authenticated webhook secures lead ingestion from the site\'s contact and audit-request forms',
      'Hunter.io verifies deliverability and OpenAI classifies each inquiry as High, Medium or Low priority',
      'Qualified leads are created or updated in HubSpot with upsert logic that prevents duplicates',
    ],
    outcomePoints: [
      'Live production website at blackcat.marketing that matches the agency\'s positioning',
      'Services are presented in a scannable, conversion-focused structure with a clear path to an audit request',
      'Manual EOD compilation fully eliminated, a consistent report lands every evening without fail',
      'Historical reports automatically archived in Google Drive for trend review',
      'Manual CRM data entry eliminated, qualified leads land in HubSpot in seconds',
      'Duplicate contact records dropped to zero with upsert logic',
      'Full audit trail across both the reporting and lead pipelines',
    ],
    deliverySteps: [
      'Discovery sessions to define site positioning, audience and conversion goals, alongside a reporting and lead-flow audit',
      'Mapped user journeys from homepage hero through service pillars to contact and audit-request actions',
      'Designed and built responsive layouts for desktop, tablet and mobile',
      'Developed conversion-focused service pages with structured content and clear CTAs',
      'Built the ClickUp and GoHighLevel integrations and the data merge/format layer in n8n',
      'Integrated Google Gemini for the AI-generated narrative EOD summary',
      'Configured Slack, email and Google Drive distribution for the daily report, scheduled at 6 PM weekdays with error alerting',
      'Secured lead ingestion with a JWT-authenticated webhook and integrated Hunter.io verification',
      'Implemented OpenAI-based lead scoring and HubSpot contact creation/update with duplicate detection',
      'Deployed the live site and validated all automation flows end to end',
    ],
    testimonial: {
      quote: 'The new site finally looks like the level of work we deliver for clients. Clean, direct, and built to convert. On top of that, the reporting just runs, 6 PM every day, and leads land in HubSpot ready to action instead of sitting in someone\'s inbox.',
    },
    tools: ['Figma', 'React', 'Tailwind CSS', 'Vercel', 'n8n', 'Google Gemini', 'ClickUp', 'GoHighLevel', 'Slack', 'Google Drive', 'OpenAI API', 'Hunter.io', 'HubSpot CRM', 'Google Sheets', 'JWT Authentication'],
    screenshots: [
      { src: '/assets/Black_cat_website (1).png', caption: 'Homepage, hero and conversion messaging' },
      { src: '/assets/Black_cat_website (2).png', caption: 'Service pillars and lead generation layout' },
      { src: '/assets/Full workflow - EOD.PNG', caption: 'Full n8n EOD report workflow, end-to-end pipeline' },
      { src: '/assets/Clickup.PNG', caption: 'ClickUp, daily task completion data fetch' },
      { src: '/assets/GHL.PNG', caption: 'GoHighLevel, sales pipeline data retrieval' },
      { src: '/assets/Slack.PNG', caption: 'Slack, automated report distribution' },
      { src: '/assets/full workflow.png', caption: 'Full n8n workflow, lead intake pipeline' },
      { src: '/assets/webhook.png', caption: 'JWT-secured webhook, lead ingestion' },
      { src: '/assets/hubspot.png', caption: 'HubSpot CRM, contact creation & sync' },
    ],
  },
  {
    slug: 'meemint-crm',
    industry: 'transport-travel-hospitality',
    services: ['custom-systems'],
    shot: 'MeemInt CRM dashboard screenshot',
    thumbnail: '/assets/meemInt-thumbnail.png',
    tag: 'Custom CRM',
    title: 'MeemInt, Transport & Hotel CRM',
    desc: 'A custom CRM portal built on the MERN stack centralising booking management, customer records, invoicing, route planning, and fleet operations for transport and hotel businesses in one unified platform.',
    m1v: 'MERN',
    m1l: 'full-stack',
    m2v: '100%',
    m2l: 'custom-built',
    challenge:
      'Transport and hotel operations were managed across disconnected tools, bookings in spreadsheets, customer records in separate files, invoices generated manually, and fleet data tracked informally. There was no single source of truth, no real-time visibility, and no way to enforce access controls across teams.',
    solution:
      'We designed and built a custom MERN stack CRM portal that centralises every operational function, bookings, customer records, invoicing, route planning, and fleet management, into a single responsive platform with role-based access and real-time dashboards.',
    outcome:
      'A modern, unified operations platform that replaced fragmented tools with a single source of truth, improving booking accuracy, reducing manual effort, and giving management real-time visibility across both transport and hotel operations.',
    tldr: [
      'Custom CRM built on the MERN stack (MongoDB, Express.js, React, Node.js)',
      'Centralised booking management, customer records, invoicing, and fleet operations',
      'Route planning module integrated directly into the operational workflow',
      'Responsive dashboards with real-time data visualisation and reporting',
      'Role-based access control, staff see only what they need',
      'Scalable architecture designed to grow with the business',
    ],
    problemPoints: [
      'Bookings managed across spreadsheets and informal tools, no unified system',
      'Customer records stored in separate files with no searchable history or audit trail',
      'Invoices generated manually, time-consuming, error-prone, and inconsistent',
      'Fleet and route planning handled informally with no visibility into availability or scheduling',
      'No role-based access, all staff had access to all data regardless of their function',
      'No real-time reporting, management had no live view of operational performance',
      'Disconnected hotel and transport operations with no shared data layer',
    ],
    solutionPoints: [
      'MERN stack CRM built from scratch, MongoDB, Express.js, React, Node.js',
      'Centralised booking module covering creation, modification, confirmation, and history',
      'Customer record management with searchable profiles, booking history, and notes',
      'Invoicing system with automated generation, PDF export, and payment status tracking',
      'Route planning module with fleet assignment and scheduling built in',
      'Role-based access control, granular permissions per user role across all modules',
      'Real-time dashboards with live data visualisation and exportable reports',
      'Responsive UI designed for both desktop operations and mobile management access',
    ],
    outcomePoints: [
      'All transport and hotel operations unified in a single platform',
      'Booking accuracy improved with a structured, validated intake workflow',
      'Manual invoicing eliminated, automated generation with payment tracking',
      'Fleet and route visibility available in real time to operations staff',
      'Role-based access enforced across every module, right data, right people',
      'Management dashboards provide live operational reporting without manual aggregation',
      'Scalable architecture ready for additional business units or locations',
    ],
    deliverySteps: [
      'Discovery sessions to map all operational workflows across transport and hotel functions',
      'Designed system architecture: MERN stack with role-based auth and modular service layer',
      'UI/UX design, responsive layouts, dashboard wireframes, and user workflow prototyping',
      'Built the React frontend with real-time data visualisation components',
      'Developed the Node.js/Express.js backend with RESTful API layer',
      'Configured MongoDB schema for bookings, customers, invoices, routes, and fleet records',
      'Implemented role-based access control with JWT authentication',
      'Built invoicing module with automated PDF generation and payment status tracking',
      'Integrated route planning and fleet management modules',
      'End-to-end QA, performance testing, and responsive design validation',
      'Deployment and handover with documentation for ongoing management',
    ],
    testimonial: {
      quote: 'I kept saying we would sort out the spreadsheet situation eventually. Silver Axis actually sorted it. The system is clean, the team picked it up fast, and I genuinely cannot imagine going back.',
    },
    tools: ['React', 'Node.js', 'MongoDB', 'Express', 'TypeScript', 'Docker'],
    screenshots: [
      { src: '/assets/mi (1).png', caption: 'MeemInt CRM, main dashboard overview' },
      { src: '/assets/mi (2).png', caption: 'Booking management and customer records' },
      { src: '/assets/mi (3).png', caption: 'Reporting and data visualisation' },
    ],
  },
  {
    slug: 'trade-with-allah',
    industry: 'on-demand-matching-platforms',
    services: ['web-mobile', 'ai-automation'],
    shot: 'Trade with ALLAH app and WhatsApp automation screenshot',
    thumbnail: '/assets/Trade with ALLAH.png',
    tag: 'Mobile App · AI Automation · Location Matching',
    title: 'Trade with ALLAH, Location-Matched Volunteer Network',
    desc: 'A faith-driven platform that matches people in need with verified local volunteers in real time, delivered as both a native mobile app and a WhatsApp-native automation layer so no one needs to install anything to give or get help.',
    m1v: 'Live',
    m1l: 'on App Store & Play Store',
    m2v: '24/7',
    m2l: 'automated matching & coordination',
    liveUrl: 'https://apps.apple.com/pk/app/trade-with-allah/id6757193179',
    challenge:
      'Many individuals and families face urgent needs but struggle to find timely help, while willing volunteers have no visibility into who needs assistance nearby. Coordination happened informally through WhatsApp group chats, staff manually read and routed every message, requests had no structure or media support, conversations had no memory between messages, and multilingual users were either ignored or needed a bilingual staff member to relay for them.',
    solution:
      'We built Trade With Allah as two connected surfaces sharing one matching engine. A mobile app lets beneficiaries create assistance requests with photos, voice notes, or video, and verified volunteers receive real-time notifications for nearby requests matching their categories and availability. Underneath it, a self-hosted n8n automation layer on the WhatsApp Business API replaces the old group chats entirely, a state-based conversation engine remembers where each user is in a workflow, dynamically matches volunteers by querying Airtable in real time, translates messages with AI for multilingual users, and parses raw location pins into structured data used directly in matching and routing.',
    outcome:
      'A trusted, location-aware volunteer network that connects people in need with community helpers faster than any informal channel, reachable either through a dedicated app or plain WhatsApp, with full accountability, category-based filtering, and real-time request tracking from submission to completion.',
    tldr: [
      'Faith-driven platform connecting people in need with trusted local volunteers',
      'One matching engine powers both a native mobile app and a WhatsApp-native automation layer',
      'Smart location-based matching surfaces the right volunteer for each request',
      'Assistance requests support photos, voice notes, and video for full context',
      'State-based conversation engine on WhatsApp remembers context across messages, no re-explaining needed',
      'AI translation layer serves multilingual users automatically, no bilingual staff required',
      'Verified volunteer approval system and full audit trail in Airtable for every request',
      'Full development lifecycle: requirements, design, development, QA, App Store submission',
    ],
    problemPoints: [
      'People in urgent need had no reliable way to quickly find help in their local community',
      'Willing volunteers had no visibility into who needed assistance nearby',
      'All coordination happened in WhatsApp group chats, requests and assignments were buried in conversation threads',
      'Staff manually read every incoming message and assigned it to the right person by hand',
      'No conversation state, users had to repeat context every time they sent a new message',
      'No verification system, beneficiaries had no way to trust who was responding to their request',
      'Requests lacked structure, no categories, no media support, no way to communicate context clearly',
      'Multi-language users were either ignored or required a bilingual staff member to relay messages',
      'Location data, where shared at all, was raw pins with no way to process or act on it programmatically',
    ],
    solutionPoints: [
      'Beneficiaries create structured assistance requests with photos, voice notes, and video for full context, in-app or via WhatsApp',
      'Category-based system (Food, Medicine, Education, Financial Aid, Transportation, and more) for precise matching',
      'Smart location-based matching notifies verified volunteers about nearby relevant requests in real time',
      'State-based conversation engine on WhatsApp remembers where each user is in a workflow, no lost context between messages',
      'Dynamic volunteer matching engine queries Airtable in real time to find and assign the best-fit volunteer',
      'Verified volunteer approval system, every volunteer is reviewed before accessing either surface',
      'AI translation layer detects language and localises outbound WhatsApp messages automatically',
      'Geolocation processing converts raw location pins into structured geographic data used directly in matching logic',
      'Real-time request tracking from pending through to completed, visible to both parties on either surface',
      'Biometric authentication (Face ID / fingerprint) and OTP verification for fast, secure app sign-in',
    ],
    outcomePoints: [
      'Launched live on iOS App Store and Google Play Store, with WhatsApp as a zero-install alternative',
      'Faster response times for people in need through location-aware volunteer matching on both surfaces',
      'Manual group-chat coordination fully replaced, staff no longer read and route messages by hand',
      'Verified and accountable volunteer network, trust built into the platform by design',
      'Multilingual users served automatically with no bilingual staff dependency',
      'Full request and interaction audit trail logged in Airtable for reporting and accountability',
      'Modular automation architecture means new workflow sequences ship independently without touching core logic',
    ],
    deliverySteps: [
      'Stakeholder workshops to map beneficiary and volunteer journeys end-to-end across both surfaces',
      'Defined system architecture: shared location-matching engine, real-time notifications, media uploads, WhatsApp state machine',
      'UI/UX design, wireframes, interactive prototypes, and usability testing for the mobile app',
      'Built the cross-platform mobile app (iOS + Android)',
      'Set up self-hosted n8n server and configured WhatsApp Business API webhook integration',
      'Built the state-based message routing engine to evaluate and direct incoming WhatsApp messages',
      'Designed Airtable schema shared across both surfaces for user data, workflow state, and request tracking',
      'Implemented smart location-based matching and category-based filtering with media attachment support',
      'Integrated AI translation service for real-time multilingual message localisation',
      'Implemented biometric authentication (Face ID / fingerprint) and OTP verification in the app',
      'Brute-force and route testing, performance optimisation, and QA sign-off across both surfaces',
      '14-day closed beta on Play Store, privacy policy and T&C documentation',
      'Submitted and released on App Store and Google Play Store, automation layer live in parallel',
    ],
    testimonial: {
      quote: 'The app does exactly what we needed it to do, it connects people who need help with people who want to help, and it does it quickly. The location matching works well, the notification system is reliable, and the overall experience is clean. Silver Axis delivered everything we asked for and were great to work with throughout.',
    },
    tools: ['React Native', 'Node.js', 'PostgreSQL', 'Firebase', 'TypeScript', 'Google Maps API', 'n8n', 'WhatsApp Business API', 'Airtable', 'OpenAI API'],
    screenshots: [
      { src: '/assets/twa (1).png', caption: 'Home, request feed and navigation' },
      { src: '/assets/twa (5).png', caption: 'Request detail, location, media, and volunteer info' },
      { src: '/assets/twa (6).png', caption: 'Sign in, biometric and OTP authentication' },
      { src: '/assets/twa (7).png', caption: 'Accept & help, volunteer request flow' },
      { src: '/assets/twa (8).png', caption: 'Ask for help, category and location selection' },
      { src: '/assets/whatsapp_n8n_workflow.png', caption: 'Main n8n workflow, WhatsApp message orchestration' },
      { src: '/assets/whatsapp_chat_registration_flow.png', caption: 'Chat registration flow, state-based onboarding' },
      { src: '/assets/whatsapp_volunteer_approval_flow.png', caption: 'Volunteer approval flow, multi-step routing' },
      { src: '/assets/airtable_requests_table.png', caption: 'Airtable, requests table & audit log' },
      { src: '/assets/airtable_automation_agent.png', caption: 'Airtable, automation agent configuration' },
    ],
  },
  {
    slug: 'smart-backload',
    industry: 'transport-travel-hospitality',
    services: ['web-mobile'],
    shot: 'SmartBackload app screenshot',
    thumbnail: '/assets/screens-SB.png',
    tag: 'Web + Mobile',
    title: 'Smart Backload',
    desc: 'Smart Backload connects available trucks with freight in real time to eliminate empty return trips. Transporters share capacity, brokers post bids, and intelligent matching ensures fast, efficient deals, boosting utilization, reducing costs, and improving delivery speed.',
    m1v: 'Live',
    m1l: 'on App Store & Play Store',
    m2v: '60s',
    m2l: 'to post a load',
    liveUrl: 'https://smartbackload.com',
    challenge:
      'A large portion of trucks return empty after completing deliveries, costing transporters earnings and leaving brokers scrambling to find reliable capacity at short notice. There was no structured marketplace to connect the two sides in real time.',
    solution:
      'We designed and built Smart Backload, a cross-platform mobile app and web platform where transporters publish available capacity through Auction or RFQ modes, and brokers bid or submit quotes in a live, competitive environment with intelligent matching.',
    outcome:
      'Smart Backload launched on both the App Store and Google Play Store. Transporters fill empty return trips with paying loads, brokers get faster and more reliable access to capacity, and the platform handles the entire deal lifecycle from posting to finalisation.',
    tldr: [
      'Real-time freight marketplace connecting transporters and freight brokers',
      'Auction and RFQ (Request for Quotation) modes for structured, competitive pricing',
      'Cross-platform mobile app (iOS + Android) and responsive web platform',
      'Secure login with Face ID / fingerprint + WhatsApp OTP authentication',
      'Load posted in under 60 seconds with templates and one-click reposting',
      'Smart auction engine: prevents last-minute bids, handles drop-offs, next-bidder consent flow',
      'Dual-role system, users switch between broker and transporter seamlessly',
      'Real-time notifications for all key events across the deal lifecycle',
    ],
    problemPoints: [
      'Trucks completing deliveries return empty, wasted capacity and lost earnings for transporters',
      'Brokers and shippers had no structured channel to quickly find reliable available trucks',
      'No transparent pricing mechanism, deals were informal, inconsistent, and slow to close',
      'Logistics coordination happened across scattered phone calls, WhatsApp groups, and spreadsheets',
      'No audit trail or record of bids, quotes, or deal history for either party',
      'Repeat shipments on frequent routes required starting the whole process from scratch each time',
    ],
    solutionPoints: [
      'Transporters publish available capacity with route, timing, and capacity details in under 60 seconds',
      'Auction mode lets brokers compete in a live bidding environment with anti-snipe rules and drop-off handling',
      'RFQ mode lets brokers submit private quotes for structured, negotiated deals',
      'Dual-role account system, a single user can act as both broker and transporter with a one-tap role switch',
      'Load templates and one-click reposting eliminate repetitive data entry for frequent routes',
      'Contact details hidden until a deal is finalised, protecting both parties throughout the bidding process',
      'WhatsApp OTP + biometric login (Face ID / fingerprint) for fast, secure authentication',
      'Real-time push notifications keep both parties updated at every stage of the deal',
    ],
    outcomePoints: [
      'Live on iOS App Store and Google Play Store',
      'Empty return trips turned into revenue-generating loads for transporters',
      'Brokers access a competitive, transparent marketplace instead of scattered phone calls',
      'Load posting takes under 60 seconds, templates and reposting eliminate repetitive work',
      'Smart auction engine ensures fair, tamper-resistant deal closure',
      'Dual-role system removes friction for logistics professionals who operate on both sides',
      'Full deal history and audit trail available in-app for both parties',
    ],
    deliverySteps: [
      'Stakeholder workshops to map the full broker and transporter journey end-to-end',
      'Defined high-level architecture: mobile-first, cross-platform, real-time event-driven core',
      'UI/UX design, wireframes, interactive prototypes, and usability iterations',
      'Built the cross-platform mobile app (iOS + Android) and responsive web platform',
      'Implemented auction engine with anti-snipe rules, drop-off handling, and next-bidder consent flow',
      'Integrated WhatsApp OTP and biometric authentication (Face ID / fingerprint)',
      'Built real-time notification system for all deal lifecycle events',
      'Implemented load templates, one-click reposting, and dual-role account switching',
      'Brute-force and route testing, performance optimisation, and QA sign-off',
      '14-day closed beta on Play Store, privacy policy and T&C documentation',
      'Submitted and released on App Store and Google Play Store',
      'Post-launch maintenance and prompt issue resolution',
    ],
    testimonial: {
      quote: 'The auction logic is genuinely impressive. Anti-snipe rules, drop-off handling, next-bidder flow, it all just works. We had drivers posting loads on day one without any hand-holding.',
    },
    tools: ['React Native', 'Node.js', 'PostgreSQL', 'WebSockets', 'Firebase', 'TypeScript'],
    screenshots: [
      { src: '/assets/screens-SB.png', caption: 'Smart Backload, app screens overview' },
      { src: '/assets/Website -SB.jpeg', caption: 'Smart Backload, web platform' },
      { src: '/assets/Play Store -SB.jpeg', caption: 'Smart Backload, Google Play Store listing' },
      { src: '/assets/App store -SB.PNG', caption: 'Smart Backload, Apple App Store listing' },
    ],
  },
  {
    slug: 'ue-motors-dealership',
    industry: 'transport-travel-hospitality',
    services: ['web-mobile', 'custom-systems'],
    shot: 'UE Motors dealership website screenshot',
    thumbnail: '/assets/EUMtoros_Thumbnail.png',
    tag: 'Web + Backend',
    title: 'UE Motors, Car Dealership Website',
    desc: 'A modern car dealership website for UE Motors, a UK-based used vehicle dealer, with intuitive inventory search, finance and part-exchange flows, and a backend built on PostgreSQL and deployed on AWS.',
    m1v: 'UK',
    m1l: 'used vehicle dealer',
    m2v: 'AWS',
    m2l: 'production deployment',
    liveUrl: 'https://www.uemotors.co.uk/',
    challenge:
      'UE Motors needed a professional online presence to showcase used vehicle stock, but their previous setup made it hard for buyers to browse inventory, enquire about vehicles, or explore finance and part-exchange options. Listings were difficult to manage, and the experience did not work well across mobile devices.',
    solution:
      'We designed and developed a modern dealership website with an intuitive vehicle inventory and search experience, integrated stock listings, finance, part-exchange, and inquiry sections, backed by a PostgreSQL database and deployed on AWS for reliable performance.',
    outcome:
      'A responsive, conversion-focused dealership platform that helps UE Motors showcase inventory professionally, capture vehicle enquiries, and give buyers a smooth path from browsing to contact across desktop, tablet, and mobile.',
    tldr: [
      'Designed and developed a modern car dealership website for UE Motors',
      'Built an intuitive vehicle inventory and search experience',
      'Responsive layouts optimized for desktop, tablet, and mobile',
      'Integrated stock listings, finance, part-exchange, and vehicle inquiry sections',
      'PostgreSQL backend for inventory and enquiry management',
      'Deployed on AWS for reliable production hosting',
    ],
    problemPoints: [
      'Used vehicle stock was hard to browse and search online, limiting buyer engagement',
      'No structured way for customers to enquire about specific vehicles from listing pages',
      'Finance, part-exchange, and inquiry journeys were missing or disconnected',
      'Mobile browsing experience did not match how most car buyers research vehicles',
      'Inventory updates required manual effort with no reliable backend system',
      'The dealership lacked a professional online presence to support lead generation',
    ],
    solutionPoints: [
      'Designed and developed a modern car dealership website for UE Motors, a UK-based used vehicle dealer',
      'Built an intuitive vehicle inventory and search experience for fast stock discovery',
      'Created responsive layouts optimized for desktop, tablet, and mobile devices',
      'Integrated stock listings, finance, part-exchange, and vehicle inquiry sections',
      'Implemented a PostgreSQL backend to manage inventory, enquiries, and operational data',
      'Deployed the platform on AWS for scalable, reliable production hosting',
      'Focused on user experience, lead generation, and conversion optimization throughout',
    ],
    outcomePoints: [
      'Professional online presence that showcases inventory with clarity and trust',
      'Buyers can search stock and submit vehicle enquiries with fewer steps',
      'Finance and part-exchange sections support stronger conversion paths',
      'Responsive experience works consistently across desktop, tablet, and mobile',
      'Backend on PostgreSQL gives the dealership a reliable system for listings and leads',
      'AWS deployment supports stable performance for customer-facing traffic',
    ],
    deliverySteps: [
      'Discovery sessions to map inventory, enquiry, finance, and part-exchange workflows',
      'UI/UX design for homepage, stock listings, vehicle detail pages, and enquiry flows',
      'Built responsive frontend layouts for desktop, tablet, and mobile',
      'Developed vehicle inventory search, filtering, and listing detail experiences',
      'Integrated finance, part-exchange, and vehicle inquiry sections',
      'Built PostgreSQL backend for stock management and customer enquiry handling',
      'Configured AWS deployment for production hosting and reliability',
      'Tested key user journeys and launched the live dealership platform',
    ],
    testimonial: {
      quote: 'Our old site was basically a brochure nobody used. Now people actually browse stock on their phone and message us about specific cars. Still getting used to updating listings ourselves, but it beats chasing someone every time we sell a motor.',
    },
    tools: ['React', 'Node.js', 'PostgreSQL', 'AWS', 'TypeScript', 'Tailwind CSS'],
    screenshots: [
      { src: '/assets/EUMotors (1).png', caption: 'Homepage and dealership branding' },
      { src: '/assets/EUMotors (2).png', caption: 'Vehicle inventory and search experience' },
      { src: '/assets/EUMotors (3).png', caption: 'Vehicle detail, finance, and enquiry flow' },
    ],
  },
  {
    slug: 'ika-motors-dealership',
    industry: 'transport-travel-hospitality',
    services: ['web-mobile'],
    shot: 'IKA Motors car dealership website screenshot',
    thumbnail: '/assets/ika.png',
    tag: 'Web Design · Dealership Platform',
    title: 'IKA Motors, Car Dealership Website',
    desc: 'A full rebuild of IKA Motors\' online showroom, a Dudley-based used car dealer, transforming a static vehicle listing into a live, searchable inventory platform with built-in finance, part-exchange, and delivery tools.',
    m1v: 'Live',
    m1l: 'production dealership site',
    m2v: '52+',
    m2l: 'vehicles searchable in real time',
    liveUrl: 'https://www.ikamotors.co.uk/',
    challenge:
      'IKA Motors had a strong reputation, rated highly on AutoTrader and Google, and a genuinely large stock of used vehicles, but their online listing did not reflect any of it. Buyers had no real way to search or filter stock, vehicle pages carried little more than a photo and a price, and there was no way to check finance costs, value a part-exchange, or work out delivery without picking up the phone. On mobile, where most car buyers actually browse, the experience broke down further.',
    solution:
      'We rebuilt IKA Motors\' website around a live, filterable inventory, replacing the static listing with a homepage search widget (make, model, min/max price), category browsing by body type, and a "latest arrivals" feed pulling straight from current stock. Every vehicle now gets its own detail page with a full photo gallery, spec sheet, and description, backed by three tools buyers previously had to call for: a finance calculator showing monthly price and representative APR, a part-exchange valuation flow that takes a reg plate and mileage, and a postcode-based delivery cost calculator. We also surfaced their AutoTrader and Google review scores site-wide and added an embedded map and WhatsApp chat for instant contact.',
    outcome:
      'IKA Motors now has a dealership site that matches the quality of the stock and reputation behind it. Buyers can go from browsing to an enquiry, finance application, or part-exchange valuation without leaving the site or picking up the phone, and the dealership\'s AutoTrader and Google ratings are now front and centre instead of buried on third-party listing sites.',
    tldr: [
      'Rebuilt a static vehicle listing into a live, searchable inventory platform',
      'Homepage search widget filters by make, model, and price range across 52+ vehicles',
      'Category browsing by body type (Cars, Vans, Hatchback, SUV, Saloon) with live stock counts',
      'Individual vehicle pages with full photo galleries, spec sheets, and descriptions',
      'Built-in finance calculator showing monthly price and representative APR per vehicle',
      'Reg-lookup part-exchange valuation tool and postcode-based delivery cost calculator',
      'AutoTrader and Google review scores surfaced site-wide for trust',
      'Embedded location map and WhatsApp chat widget for instant buyer contact',
      'Fully responsive across desktop, tablet, and mobile',
    ],
    problemPoints: [
      'Vehicle stock was listed statically with no way to search or filter by make, model, or price',
      'Vehicle pages showed little more than a photo and price, no spec sheet, gallery, or detail',
      'No finance tool, buyers had to call to find out monthly cost or APR on a vehicle',
      'No part-exchange valuation path, every trade-in enquiry required a phone call',
      'No delivery cost information available without contacting the dealership directly',
      'Strong AutoTrader and Google ratings existed but were not visible anywhere on the dealership\'s own site',
      'Mobile experience did not hold up, despite most car buyers researching stock on their phones',
    ],
    solutionPoints: [
      'Built a homepage search widget filtering live stock by make, model, and min/max price',
      'Added category browsing by body type with real-time stock counts (Cars, Vans, Hatchback, SUV, Saloon)',
      '"Latest arrivals" feed surfaces newly listed stock directly on the homepage',
      'Individual vehicle detail pages with full photo galleries, spec sheets, and free-text descriptions',
      'Finance calculator on every vehicle page showing monthly price and a representative APR example',
      'Part-exchange valuation tool, buyers enter their reg plate and mileage to start a trade-in enquiry',
      'Postcode-based delivery cost calculator built into every vehicle page',
      'AutoTrader and Google review scores displayed site-wide to reinforce trust at the point of decision',
      'Embedded interactive map showing the Dudley showroom location, plus a WhatsApp chat widget for instant contact',
      'Fully responsive layouts rebuilt for desktop, tablet, and mobile',
    ],
    outcomePoints: [
      'Live production dealership site presenting 52+ vehicles in a searchable, filterable inventory',
      'Buyers can search, compare, and shortlist vehicles without calling the showroom',
      'Finance, part-exchange, and delivery questions are now answered on-site instead of over the phone',
      'AutoTrader and Google ratings visible throughout the site build immediate trust with new visitors',
      'Vehicle detail pages give buyers everything needed to make a decision, gallery, spec, price, and finance',
      'Consistent, working experience across desktop, tablet, and mobile',
    ],
    deliverySteps: [
      'Discovery session to audit the existing listing and map the buyer journey from search to enquiry',
      'Designed the homepage search, category browsing, and latest arrivals experience',
      'Built responsive layouts for desktop, tablet, and mobile',
      'Developed vehicle inventory search, filtering, and detail page templates with photo galleries',
      'Built the finance calculator, part-exchange valuation flow, and postcode delivery calculator',
      'Integrated AutoTrader and Google review scores and an embedded showroom location map',
      'Added WhatsApp chat widget for instant buyer contact',
      'Tested key buyer journeys across devices and launched the live site',
    ],
    testimonial: {
      quote: 'People can actually find what they\'re after now instead of scrolling through everything we\'ve got. The finance and part-ex tools have cut down a lot of the back-and-forth calls, and it looks the part on a phone, which is where most people are looking anyway.',
    },
    tools: ['HTML5', 'CSS3', 'JavaScript', 'Bootstrap', 'jQuery', 'Google Maps API'],
    screenshots: [
      { src: '/assets/ika1.PNG', caption: 'Homepage, live search widget and finance messaging' },
      { src: '/assets/ika2.PNG', caption: 'Category browsing and latest arrivals feed' },
      { src: '/assets/ika3.PNG', caption: 'Vehicle detail page, gallery and enquiry actions' },
      { src: '/assets/ika4.PNG', caption: 'Finance, delivery calculator, part-exchange and map' },
    ],
  },
];

export const HOME_CASES = ALL_CASES.slice(0, 2);

export function getCaseStudyBySlug(slug: string): CaseStudy | undefined {
  return ALL_CASES.find((cs) => cs.slug === slug);
}

export function filterCaseStudiesByService(service: ServiceCategorySlug | null): CaseStudy[] {
  if (!service) return ALL_CASES;
  return ALL_CASES.filter((cs) => cs.services.includes(service));
}

export function filterCaseStudiesByIndustry(industry: IndustrySlug | null): CaseStudy[] {
  if (!industry) return ALL_CASES;
  return ALL_CASES.filter((cs) => cs.industry === industry);
}

export function getIndustryCaseCount(industry: IndustrySlug): number {
  return ALL_CASES.filter((cs) => cs.industry === industry).length;
}

export function getRelatedCaseStudies(slug: string, limit = 3): CaseStudy[] {
  const current = getCaseStudyBySlug(slug);
  if (!current) return [];
  return ALL_CASES.filter((cs) => cs.slug !== slug && cs.industry === current.industry).slice(0, limit);
}
