import type { ServiceVisual } from '../types';
import { serviceImage } from '../types';

export const PRACTICE_VISUALS: Record<string, ServiceVisual> = {
  'software-development': {
    theme: 'engineering',
    involvesLayout: 'grid',
    processLayout: 'cards',
    image: serviceImage('software-development'),
    imageAlt: 'Abstract architecture diagram for custom software systems',
    feature: {
      eyebrow: 'Built to last',
      title: 'Architecture you can extend after handoff.',
      body: 'We leave seams, docs, and environments that your next hire can understand in days—not months of archaeology.',
      bullets: [
        'Clear module boundaries and API contracts',
        'Environments that mirror production behavior',
        'Ownership transfer as part of done',
      ],
      imagePosition: 'right',
    },
  },
  'web-development': {
    theme: 'web',
    involvesLayout: 'bento',
    processLayout: 'rail',
    image: serviceImage('web-development'),
    imageAlt: 'Abstract web interfaces and responsive layout frames',
  },
  'mobile-apps': {
    theme: 'mobile',
    involvesLayout: 'grid',
    processLayout: 'steps',
    image: serviceImage('mobile-apps'),
    imageAlt: 'Smartphone product interfaces on a dark studio background',
    feature: {
      eyebrow: 'Store ready',
      title: 'Native feel with release pipelines you can run.',
      body: 'Signing, beta tracks, and crash tooling ship with the app—so updates stay routine after launch.',
      bullets: [
        'iOS and Android platform respect',
        'Offline-aware flows where networks fail',
        'CI builds for TestFlight and Play',
      ],
      imagePosition: 'right',
    },
    module: {
      type: 'platforms',
      eyebrow: 'Platforms',
      title: 'Choose the mobile path that fits the product.',
      items: [
        {
          title: 'iOS native',
          meta: 'Swift',
          body: 'Deep platform UX, Apple review readiness, and performance where gestures matter.',
        },
        {
          title: 'Android native',
          meta: 'Kotlin',
          body: 'Material-aware apps that behave across device classes and OEM quirks.',
        },
        {
          title: 'Cross-platform',
          meta: 'RN / Flutter',
          body: 'Shared business logic when speed and one team matter more than pure native polish.',
        },
      ],
    },
  },
  'ai-ml': {
    theme: 'ai',
    involvesLayout: 'bento',
    processLayout: 'rail',
    image: serviceImage('ai-ml'),
    imageAlt: 'Neural network and data flow visualization for applied AI',
    feature: {
      eyebrow: 'Production AI',
      title: 'Grounded systems—not a novelty chat box.',
      body: 'Retrieval, tools, evaluation, and human approvals so AI changes operations instead of creating new risk.',
      bullets: [
        'Workflow-first use case selection',
        'Evaluation sets that catch regressions',
        'Cost and latency budgets per feature',
      ],
      imagePosition: 'left',
    },
    module: {
      type: 'loop',
      eyebrow: 'Quality loop',
      title: 'How we keep AI trustworthy after launch.',
      stages: [
        { title: 'Instrument', body: 'Log prompts, outcomes, and human overrides.' },
        { title: 'Evaluate', body: 'Golden sets and online monitors for drift.' },
        { title: 'Guard', body: 'Approvals, redaction, and fallback paths.' },
        { title: 'Improve', body: 'Prompt and retrieval changes shipped like product code.' },
      ],
    },
  },
  blockchain: {
    theme: 'chain',
    involvesLayout: 'hex',
    processLayout: 'rail',
    image: serviceImage('blockchain'),
    imageAlt: 'Abstract interconnected ledger blocks representing blockchain architecture',
    feature: {
      eyebrow: 'Minimum viable chain',
      title: 'Put on-chain only what must be shared and auditable.',
      body: 'We challenge the need for a ledger first—then design a thin trust layer with tests, upgrade paths, and ops runbooks.',
      bullets: [
        'Honest go / no-go on chain scope',
        'Contracts with invariant tests',
        'Wallet UX for non-crypto users',
      ],
      imagePosition: 'right',
    },
    module: {
      type: 'compare',
      eyebrow: 'Fit check',
      title: 'On-chain vs strong off-chain systems.',
      left: {
        title: 'Prefer on-chain when',
        items: [
          'Multiple distrusting parties need shared settlement',
          'Independent auditability is a product requirement',
          'Escrow or provenance must be verifiable externally',
        ],
      },
      right: {
        title: 'Prefer conventional systems when',
        items: [
          'A database with audit logs is enough',
          'Latency and UX cannot tolerate chain constraints',
          'The “need” is branding rather than trust mechanics',
        ],
      },
    },
  },
  'ui-ux': {
    theme: 'design',
    involvesLayout: 'bento',
    processLayout: 'steps',
    image: serviceImage('ui-ux'),
    imageAlt: 'Interface cards and design system components in a studio composition',
    feature: {
      eyebrow: 'Build-ready design',
      title: 'Systems engineering can ship without guessing.',
      body: 'Flows, states, and tokens beat pretty mockups that collapse in implementation.',
      bullets: [
        'Empty, error, and permission states included',
        'Design tokens aligned to frontend reality',
        'Prototype validation before heavy build',
      ],
      imagePosition: 'left',
    },
    module: {
      type: 'checklist',
      eyebrow: 'Design craft',
      title: 'What we refuse to skip.',
      body: 'These are the details that separate usable products from decorative screens.',
      items: [
        { title: 'Real content lengths', body: 'Design with actual copy and edge-case data.' },
        { title: 'Accessibility defaults', body: 'Contrast, focus, and touch targets from the start.' },
        { title: 'Motion with meaning', body: 'Transitions that explain state—not decorate.' },
        { title: 'Handoff pairing', body: 'Specs plus engineer walkthroughs, not PDF dumps.' },
      ],
    },
  },
  mvp: {
    theme: 'mvp',
    involvesLayout: 'grid',
    processLayout: 'cards',
    image: serviceImage('mvp'),
    imageAlt: 'Abstract launch path and product blocks for MVP development',
    feature: {
      eyebrow: 'Prove the bet',
      title: 'Smallest lovable slice—with a path past the prototype.',
      body: 'We cut scope bravely, instrument learning, and leave a foundation you can grow without a rewrite panic.',
      bullets: [
        'One primary success metric',
        'Weekly demos and written “not now” lists',
        'Launch checklist and iteration roadmap',
      ],
      imagePosition: 'right',
    },
  },
  'digital-marketing': {
    theme: 'growth',
    involvesLayout: 'bento',
    processLayout: 'rail',
    image: serviceImage('digital-marketing'),
    imageAlt: 'Abstract conversion funnel and analytics geometry for growth marketing',
    feature: {
      eyebrow: 'Product-aware growth',
      title: 'Funnels that share truth with the product.',
      body: 'Landing systems, tracking, and activation paths built so ad spend is not wasted on orphan pages.',
      bullets: [
        'Message match from ad to onboarding',
        'Clean event naming across tools',
        'Performance under paid traffic spikes',
      ],
      imagePosition: 'left',
    },
    module: {
      type: 'metrics',
      eyebrow: 'What we optimize',
      title: 'Signals that matter more than vanity traffic.',
      items: [
        { value: 'CVR', label: 'Path conversion', body: 'Landing to qualified action—not just clicks.' },
        { value: 'LCP', label: 'Speed under ads', body: 'Pages that stay fast when campaigns spike.' },
        { value: 'Match', label: 'Message integrity', body: 'Promise on the ad equals promise on the page.' },
        { value: 'Sync', label: 'CRM truth', body: 'Leads land where sales and lifecycle expect them.' },
      ],
    },
  },
  'cloud-devops': {
    theme: 'platform',
    involvesLayout: 'grid',
    processLayout: 'rail',
    image: serviceImage('cloud-devops'),
    imageAlt: 'Abstract cloud infrastructure layers and delivery pipelines',
    feature: {
      eyebrow: 'Boring deploys',
      title: 'Pipelines and platforms that make shipping routine.',
      body: 'IaC, CI/CD, and observability so release day stops being exciting—for the right reasons.',
      bullets: [
        'Reproducible environments from code',
        'Alerts tuned to real user pain',
        'Cloud spend visibility without freezing delivery',
      ],
      imagePosition: 'right',
    },
    module: {
      type: 'metrics',
      eyebrow: 'Platform outcomes',
      title: 'What “good delivery” looks like.',
      items: [
        { value: 'CI', label: 'Automated path', body: 'Tested artifacts from merge to deploy.' },
        { value: 'IaC', label: 'Reproducible', body: 'No click-ops folklore as the source of truth.' },
        { value: 'SLO', label: 'Observable', body: 'Golden signals and on-call friendly alerts.' },
        { value: '$$', label: 'Right-sized', body: 'Idle waste removed; budgets visible.' },
      ],
    },
  },
  'qa-automation': {
    theme: 'quality',
    involvesLayout: 'grid',
    processLayout: 'steps',
    image: serviceImage('qa-automation'),
    imageAlt: 'Abstract automated test pipeline and quality checkpoints',
    feature: {
      eyebrow: 'Risk-based QA',
      title: 'Coverage that protects releases—without slowing them.',
      body: 'Strategy, suites, and gates tuned to failure cost so flakes and vanity metrics do not own your CI.',
      bullets: [
        'Pyramid: fast API checks before selective E2E',
        'Flakes treated as defects',
        'Gates that block bad builds, not the team',
      ],
      imagePosition: 'left',
    },
    module: {
      type: 'checklist',
      eyebrow: 'Quality bar',
      title: 'Automation rules we hold the line on.',
      body: 'These keep suites valuable after the first sprint of enthusiasm fades.',
      items: [
        { title: 'Deterministic data', body: 'Factories and isolation over shared fragile fixtures.' },
        { title: 'Own every failure', body: 'Clear triage paths—no ignored red builds.' },
        { title: 'Parallel CI', body: 'Suites finish fast enough to matter at merge time.' },
        { title: 'Living docs', body: 'How to run, debug, and extend without archaeology.' },
      ],
    },
  },
};
